version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cic-infra-l2-dynamo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jxb6ns1xevo7"
s3_prefix = "cic-infra-l2-dynamo"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
