AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Digital Identity IPV CRI CIC API"

Parameters:
  CodeSigningConfigArn:
    Type: String
    Default: "none"
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
  Environment:
    Description: "The environment type"
    Type: "String"
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"
    ConstraintDescription: Please ensure that your Environment variable is set to either dev, build, staging, integration or production.
  PermissionsBoundary:
    Description: "The ARN of the permissions boundary to apply when creating IAM roles"
    Type: String
    Default: "none"
  SecretPrefix:
    Type: String
    Default: "none"
    Description: Secrets name prefix
  VpcStackName:
    Type: String
    Default: "platform-vpc"
    Description: The name of the VPC stack deployed.
  CommonStackName:
    Description: "The name of the stack containing the common CRI lambdas/infra"
    Type: String
    Default: "common-cri-api"

Mappings:
  EnvironmentConfiguration: # This is where you store per-environment settings.
    dev:
      logretentionindays: 3
      apiTracingEnabled: true
    build:
      logretentionindays: 3
      apiTracingEnabled: true
    staging:
      logretentionindays: 3
      apiTracingEnabled: true
    integration:
      logretentionindays: 30
      apiTracingEnabled: false
    production:
      logretentionindays: 30
      apiTracingEnabled: false
  EnvironmentVariables: # This is all the environment specific environment variables that don't belong in globals.
    dev:
      EXAMPLE: 1 # Just here as null values not allowed in tempaltes
    build:
      EXAMPLE: 1 # Just here as null values not allowed in tempaltes
    staging:
      EXAMPLE: 1 # Just here as null values not allowed in tempaltes
    integration:
      EXAMPLE: 1 # Just here as null values not allowed in tempaltes
    production:
      EXAMPLE: 1 # Just here as null values not allowed in tempaltes

Conditions:
  IsProdLikeEnvironment: !Or
    - !Equals [ !Ref Environment, staging ]
    - !Equals [ !Ref Environment, integration ]
    - !Equals [ !Ref Environment, production ]
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"
  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"
  UseSecretPrefix:
    Fn::Not:
      - Fn::Equals:
          - !Ref SecretPrefix
          - "none"

Globals:
  Function:
    VpcConfig:
      SecurityGroupIds:
        - !GetAtt LambdaEgressSecurityGroup.GroupId
      SubnetIds:
        - Fn::ImportValue:
            "Fn::Sub": "${VpcStackName}-PrivateSubnetIdA"
        - Fn::ImportValue:
            "Fn::Sub": "${VpcStackName}-PrivateSubnetIdB"
#        - Fn::ImportValue:
#            "Fn::Sub": "${VpcStackName}-PrivateSubnetIdC"
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    Timeout: 30 # seconds
    Tracing: Active
    MemorySize: 1024
    Architectures:
      - arm64
    Environment:
      Variables:
        # These should always be alphabetically organised.
        AWS_STACK_NAME: !Sub ${AWS::StackName}  # The AWS Stack Name, as passed into the template.
        COMMON_PARAMETER_NAME_PREFIX: !Ref CommonStackName  # What is this? @TODO
        POWERTOOLS_LOG_LEVEL: INFO  # The LogLevel for the AWS PowerTools LogHelper
        POWERTOOLS_METRICS_NAMESPACE: CIC-CRI # The Metric Namespace for the AWS PowerTools MetricHelper
        SECRET_PREFIX: !If [UseSecretPrefix, !Ref SecretPrefix , !Ref AWS::StackName]  # What is this? @TODO
        SQS_AUDIT_EVENT_PREFIX: CIC-F2F # The prefix to add to TxMA event messages
    AutoPublishAlias: live

Resources:

  LambdaEgressSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: >-
        Permits outbound on port 443 from within the VPC to the internet.
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow to the wider internet on port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      VpcId:
        Fn::ImportValue: !Sub "${VpcStackName}-VpcId"

  ### Start of API Gateway definition.

  CICRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      OpenApiVersion: 3.0.1
      AccessLogSetting:
        Format: "$context.requestId $context.httpMethod $context.path"
        DestinationArn: !GetAtt CICAPIGatewayAccessLogGroup.Arn
      EndpointConfiguration:
        Type: REGIONAL
      DefinitionBody:
        openapi: "3.0.1"
        info:
          version: "0.2"
          title: !Sub "${AWS::StackName} - CIC Credential Issuer Private API"

        paths:
          /userInfo:
            post:
              operationId: postUserInfo
              summary: Retrieve the JWT contained the Verified Credential(s) for a given Auth Session.
              description: >-
                Returns a JWT containing the user information and associated verified credentials as supplied by the
                biometrics vendor. Requires an access token as issued by `POST /token`, and can only be called once.
              tags:
                - Backend - CI CRI specific
              parameters:
                - $ref: '#/components/parameters/Authorization'
              responses:
                "200":
                  description: >-
                    OK - Signed Verified Credential returned as a JWT
                  headers:
                    Cache-Control:
                      schema:
                        type: "string"
                    Content-Type:
                      schema:
                        type: "string"
                    Strict-Transport-Security:
                      schema:
                        type: "string"
                    X-Content-Type-Options:
                      schema:
                        type: "string"
                    X-Frame-Options:
                      schema:
                        type: "string"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/UserInfoJwt"
                "401":
                  description: Unauthorized
                  headers:
                    Cache-Control:
                      schema:
                        type: "string"
                    Content-Type:
                      schema:
                        type: "string"
                    Strict-Transport-Security:
                      schema:
                        type: "string"
                    X-Content-Type-Options:
                      schema:
                        type: "string"
                    X-Frame-Options:
                      schema:
                        type: "string"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/OAuthErrorResponse"
                "500":
                  description: Internal Server Error
                  headers:
                    Cache-Control:
                      schema:
                        type: "string"
                    Content-Type:
                      schema:
                        type: "string"
                    Strict-Transport-Security:
                      schema:
                        type: "string"
                    X-Content-Type-Options:
                      schema:
                        type: "string"
                    X-Frame-Options:
                      schema:
                        type: "string"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/OAuthErrorResponse"
              x-amazon-apigateway-request-validator: "both"
              x-amazon-apigateway-integration:
                httpMethod: "POST"
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserInfoFunction.Arn}:live/invocations
                responses:
                  default:
                    statusCode: "200"
                passthroughBehavior: "when_no_match"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws_proxy"
          /claimedIdentity:
            post:
              parameters:
                - in: header
                  name: "session_id"
                  schema:
                    type: string
                  required: true
              responses:
                "400":
                  description: "400 response"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Error"
                "500":
                  description: "500 response"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Error"
                "200":
                  description: "200 response"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/HelloWorld"
              x-amazon-apigateway-request-validator: "both"
              x-amazon-apigateway-integration:
                httpMethod: "POST"
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CICHelloFunction.Arn}:live/invocations
                responses:
                  default:
                    statusCode: "200"
                passthroughBehavior: "when_no_match"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws_proxy"

        components:
          parameters:
            SessionHeader:
              name: session-id
              in: header
              description: A UUID generated by the Session API to act as a primary key for the SessionTable in DynamoDB
              required: true
              schema:
                type: string
          schemas:
            OAuthErrorResponse:
              type: object
              additionalProperties: true
              required:
                - error
              properties:
                error:
                  type: string
                  enum:
                    - access_denied
                    - invalid_request
                    - invalid_client
                    - invalid_grant
                    - unauthorized_client
                    - unsupported_grant_type
                    - invalid_scope
                    - server_error
                    - temporarily_unavailable
                    - unsupported_response_type
                    - authorization_pending
                  example: access_denied
                  description: >-
                    A single ASCII [USASCII] error code from the following
                error_description:
                  type: string
                  example: Access was denied as auth code was not recognised
                  description: >-
                    Human-readable ASCII [USASCII] text providing additional information, used to assist the
                    client developer in understanding the error that occurred.
                error_uri:
                  type: string
                  example: https://example.com/error1.html
                  description: >-
                    A URI identifying a human-readable web page with information about the error, used to
                    provide the client developer with additional information about the error.
            UserInfoJwt:
              type: object
              additionalProperties: true
              required:
                - sub
                - 'https://vocab.account.gov.uk/v1/credentialJWT'
              properties:
                sub:
                  type: string
                  format: uuid
                  description: >-
                    `sub` value - this should be the same as encoded in the signed JWT
                  example: 22222222-2222-2222-2222-222222222222
                'https://vocab.account.gov.uk/v1/credentialJWT':
                  type: string
                  description: >-
                    Signed JWT response with user credentials including the outcome from the biometric checks
            Authorization:
              required:
                - "client_id"
                - "request"
              type: "object"
              properties:
                client_id:
                  type: "string"
                  minLength: 1
                  example: "ipv-core-stub"
                request:
                  type: "string"
            AuthorizationResponse:
              required:
                - "redirect_uri"
                - "code"
                - "state"
              type: "object"
              properties:
                code:
                  type: "string"
                  example: "981bb74c-3b5e-462e-ba3a-abf868e5da68"
                state:
                  type: "string"
                  example: "state"
                  minLength: 1
                redirect_uri:
                  type: "string"
                  format: "uri"
                  example: "https://di-ipv-core-stub.london.cloudapps.digital/callback"
            Error:
              title: "Error Schema"
              type: "object"
              properties:
                message:
                  type: "string"
            Session:
              required:
                - "session_id"
              type: "object"
              properties:
                session_id:
                  type: "string"


        x-amazon-apigateway-request-validators:
          both:
            validateRequestBody: true
            validateRequestParameters: true

      TracingEnabled: true
      Tags:
        Product: GOV.UK Sign In
        System: F2F
        Environment: !Ref Environment
        Service: backend
        Name: CICRestApi
        Source: alphagov/di-devplatform-demo-sam-app/sam-app/template.yaml

  CICAPIGatewayAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !FindInMap [ EnvironmentConfiguration, !Ref Environment, logretentionindays ]
      Tags:
        - Key: Product
          Value: GOV.UK Sign In
        - Key: System
          Value: Dev Platform
        - Key: Environment
          Value: Demo
        - Key: Service
          Value: backend
        - Key: Name
          Value: APIGatewayAccessLogGroup

  ### End of API Gateway definition.

  ### Function Definition

  ## UserInfo
  UserInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "User-Info-${AWS::StackName}"
      Handler: UserInfoHandler.lambdaHandler
      CodeUri: ../src/
      Runtime: nodejs18.x
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: F2F CRI
          SESSION_TABLE: !Sub "{{resolve:ssm:/${CommonStackName}/SessionTableName}}"
          EXAMPLE: !FindInMap [ EnvironmentVariables, !Ref Environment, EXAMPLE ]
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
        - DynamoDBWritePolicy:
            TableName: !Sub "{{resolve:ssm:/${CommonStackName}/SessionTableName}}"
        - DynamoDBReadPolicy:
            TableName: !Sub "{{resolve:ssm:/${CommonStackName}/SessionTableName}}"
        - Statement:
            - Sid: KMSSignPolicy
              Effect: Allow
              Action:
                - kms:Sign
                - kms:Verify
              Resource: !Sub "arn:aws:kms:eu-west-2:060113405249:key/{{resolve:ssm:/${CommonStackName}/verifiableCredentialKmsSigningKeyId}}"
      Events:
        userInfo:
          Type: Api
          Properties:
            Path: /userInfo
            Method: post
            RestApiId: !Ref CICRestApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - UserInfoHandler.ts

  UserInfoFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/User-Info-${AWS::StackName}"
      RetentionInDays: !FindInMap [ EnvironmentConfiguration, !Ref Environment, logretentionindays ]

  UserInfoFunctionLogsSubscriptionFilterCSLS:
    Type: AWS::Logs::SubscriptionFilter
    Condition: IsProdLikeEnvironment
    Properties:
      DestinationArn: "arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython"
      FilterPattern: ""
      LogGroupName: !Ref UserInfoFunctionLogGroup

  UserInfoFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UserInfoFunction
      Principal: apigateway.amazonaws.com

  # ClaimedIdentity
  CICHelloFunction:
    Type: AWS::Serverless::Function
    DependsOn: CICHelloFunctionLogGroup
    Properties:
      FunctionName: !Sub "CIC-Hello-${AWS::StackName}"
      Handler: ClaimedIdentityHandler.lambdaHandler
      CodeUri: ../src/
      Runtime: nodejs18.x
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: F2F CRI
          SESSION_TABLE: !Sub "{{resolve:ssm:/${CommonStackName}/SessionTableName}}"
          EXAMPLE: !FindInMap [ EnvironmentVariables, !Ref Environment, EXAMPLE ]
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
        - DynamoDBWritePolicy:
              TableName: !Sub "{{resolve:ssm:/${CommonStackName}/SessionTableName}}"
        - DynamoDBReadPolicy:
              TableName: !Sub "{{resolve:ssm:/${CommonStackName}/SessionTableName}}"
      Events:
        claimedIdentity:
          Type: Api
          Properties:
            Path: /claimedIdentity
            Method: post
            RestApiId: !Ref CICRestApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
        - ClaimedIdentityHandler.ts

  CICHelloFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/CIC-Hello-${AWS::StackName}"
      RetentionInDays: !FindInMap [ EnvironmentConfiguration, !Ref Environment, logretentionindays ]

  CICHelloFunctionLogsSubscriptionFilterCSLS:
    Type: AWS::Logs::SubscriptionFilter
    Condition: IsProdLikeEnvironment
    Properties:
      DestinationArn: "arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython"
      FilterPattern: ""
      LogGroupName: !Ref CICHelloFunctionLogGroup

  CICHelloFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CICHelloFunction
      Principal: apigateway.amazonaws.com

Outputs:

  CICApiGatewayId:
    Description: "API GatewayID of the CIC CRI API"
    Value: !Sub "${CICRestApi}"
    Export:
      Name: !Sub ${AWS::StackName}-CICApiGatewayId
