openapi: 3.0.0
info:
  title: JWKS
  version: 1.0.0
  description: JWKS

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

paths:
  /.well-known/jwks.json:
    get:
      operationId: getWellKnownJwks
      summary: Retrieve the encryption public keys in JWKS format.
      description: >-
        Return the current valid public keys used to encrypt JWTs issued by the service as a JSON Web Key Set.
      tags:
        - Static
      responses:
        "200":
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Cache-Control:
              schema:
                type: "string"
            Content-Type:
              schema:
                type: "string"
            Strict-Transport-Security:
              schema:
                type: "string"
            X-Content-Type-Options:
              schema:
                type: "string"
            X-Frame-Options:
              schema:
                type: "string"
            Content-Security-Policy:
              schema:
                type: "string"
            Feature-Policy:
              schema:
                type: "string"
            Referrer-Policy:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                type: object
                properties:
                  keys:
                    type: array
                    items:
                      type: object
                      properties:
                        kid:
                          type: string
                        kty:
                          type: string
                        alg:
                          type: string
                        use:
                          type: string
                        e:
                          type: string
                        n:
                          type: string
              examples:
                success:
                  value:
                    {
                      "keys": [
                        {
                          "kty": "RSA",
                          "n": "kOBby1nEUcKc-94zIa2qCyqDSE1-2bLWkVjeF3DWY_0v2j9wlLSaR6asONen_HP40wftLOSPYRcKYv6Cjz3LOY7aQYznX14EXSgJxrDwQ7AleX2VS_HB34LMZEa3xmSSH7pLtw_vmJgCNss0zDQLCz1sQwZxlqphF18FdTTUrXbJ9Qk3xIrEzvL2naO2r6WoLBQ9tSr2Sz9TTcJQptfh6hOAHm66oPA6F9uCmbTDEQeI-wLiMMArtcKrGiPAFluo8f0qNkzLRMFIqyadnZ9OZ5u0-H_urOkmLJ2nbAnyTcO-9QeDlomdEMz3yEaJeUoq-jnPpVEfIbd8-07fl7M27w",
                          "e": "AQAB",
                          "use": "enc",
                          "alg": "RS256",
                          "kid": "da48d440-8e51-4383-9a3a-b91ce5adcf2a"
                        }
                      ]
                    }
        "500":
          description: "Internal Server Error"
          headers:
            Cache-Control:
              schema:
                type: "string"
            Content-Type:
              schema:
                type: "string"
            Strict-Transport-Security:
              schema:
                type: "string"
            X-Content-Type-Options:
              schema:
                type: "string"
            X-Frame-Options:
              schema:
                type: "string"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ "JsonWebKeysBucketApiRole", "Arn" ]
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:s3:path/${JsonWebKeysBucket}/.well-known/jwks.json"
        responses:
          "200":
            statusCode: "200"
            description: OK
            responseParameters:
              method.response.header.Content-Type: "'application/json'"
            contentHandling: "CONVERT_TO_TEXT"
          default:
            statusCode: "500"
            responseParameters:
              method.response.header.Content-Type: "'text/plain'"
        passthroughBehavior: "when_no_match"
        httpMethod: "GET"
        type: "aws"