version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cic-cri-api-v1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1senvf3mhojv"
s3_prefix = "cic-cri-api-v1"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "CodeSigningEnabled=\"true\" CodeSigningConfigArn=\"none\" Environment=\"build\" PermissionsBoundary=\"none\" SecretPrefix=\"none\" AuditEventNamePrefix=\"/common-cri-parameters/AuditEventNamePrefix\" CriIdentifier=\"/common-cri-parameters/CriIdentifier\" CommonStackName=\"common-cri-api\""
image_repositories = []
