name: Pre-merge checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  # For now do not require sam validate at pre-merge state
  # sam-validate:
  #   name: SAM Validate
  #   runs-on: ubuntu-latest
  #   env:
  #     AWS_REGION: eu-west-2
  #   permissions:
  #     id-token: write
  #     contents: read
    # defaults:
    #   run:
    #     shell: bash
    #     working-directory: infrastructure/lambda/template.yaml
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        # Need to confirm whether submodules can be removed or not
        # with:
        #   submodules: true
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.56.0
      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.GH_VALIDATE_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: SAM Validate
        run: |
          sam validate -t infrastructure/lambda/template.yaml
      - name: SAM Build
        run: |
          sam build -t infrastructure/lambda/template.yaml
    lint:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-function:
            - hello-world
      steps:
        - name: Pull Repository
          uses: actions/checkout@v3
        - name: Set-up Node 16
          uses: actions/setup-node@v3
          with:
            node-version: '16'
        # Uncomment when lambda will be added to BE
        - name: NPM Install
          working-directory: ./lambdas/${{ matrix.node-function }}
          run: npm install
        - name: run Lint
          working-directory: ./lambdas/${{ matrix.node-function }}
          run: npm run lint

  # Uncomment when a function with tests is added
  # run-unit-tests-node:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-function:
  #         - hello-world
  #   steps:
  #     - name: Pull Repository
  #       uses: actions/checkout@v3
  #     - name: Set-up Node 16
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '16'
  #     - name: NPM Install
  #       working-directory: ./lambda-functions/${{ matrix.node-function }}
  #       run: npm install
  #     - name: run node tests
  #       working-directory: ./lambda-functions/${{ matrix.node-function }}
  #       run: npm run test

  # Below is commented out until a Sonar token is provisioned for this repo
  # sonarcloud:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         # Disabling shallow clone is recommended for improving relevancy of reporting
  #         fetch-depth: 0
  #     - name: SonarCloud Scan
  #       uses: sonarsource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}