name: Pre-merge checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:

  style-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-function:
          - claimedidentity
    steps:
      - name: Pull Repository
        uses: actions/checkout@v3
      - name: Set-up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: NPM Install
        working-directory: ./src/
        run: npm install
      - name: Run Lint
        working-directory: ./src/
        run: npm run lint
      - name: Run Tests
        run: npm run test:unit  
        working-directory: ./src/
      - name: Run Infra checks
        run: npm run test:infra
        working-directory: ./src/

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-function:
          - claimedidentity
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # - name: compile
      #   working-directory: ./lambdas/${{ matrix.node-function }}
      #   run: npm run compile


# comment out when unit test is added
  # run-unit-tests:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3

# Comment out when unit test is added
# run-unit-tests-node:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-function:
#           - hello-world
#     steps:
#       - name: Pull Repository
#         uses: actions/checkout@v3
#       - name: Set-up Node 16
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#       - name: NPM Install
#         working-directory: ./lambdas/${{ matrix.node-function }}
#         run: npm install
#       - name: run node tests
#         working-directory: ./lambdas/${{ matrix.node-function }}
#         run: npm run test

  # run-sonar-analysis:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - run-unit-tests
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

